### ISSUE TITLE
ViLa复现结果、和FiVE的同一backbone复现结果相关

### ISSUE THREAD

**Issue by code1007** [Jiangbo-Shi/ViLa-MIL#12]
您好！您的工作非常有逻辑性，但是我们在尝试复现您的工作时出现了一些问题：
1、最终出现5组结果，论文展示的结果是对这5组结果取平均值还是取最优结果？
2、我们注意到2024年有相似的工作FiVE，FiVE中相同任务的各项评价指标都明显高于您的工作，并且让我们非常困惑的是，FIVE中展现的对于其他论文的复现结果也都要比您工作中的复现结果高，比如TransMIL，FiVE中的AUC、Acc、F1都要显著高于您论文中给出的复现结果，请问这是什么原因？
![屏幕截图 2024-09-14 133222](https://github.com/user-attachments/assets/0abf52f7-d6c7-4276-9bc7-1037a18e7699)
![11](https://github.com/user-attachments/assets/2a362c9d-c56a-4bbc-9095-49e0b7e367ea)

非常期待您的回复，感谢！

**Comment by Jiangbo-Shi** [comment]
1、最终结果是5折平均值；
2、FiVE采用的Backbone是DSMIL工作提出的，在病理数据上进行过预训练；我们直接采用的是通用领域的CLIP。在few-shot场景下，少量训练样本对于模型性能的影响通常是显著的。两个工作采用数据预处理方式（patch size, magnification等）、数据集划分都是不同的。另外，FiVE引入了病理报告进行预训练，本文所提出的是一种参数高效的微调框架，只依赖切片标签，实验设置和场景均是不同的，结果不具有可比性。
