### ISSUE TITLE
Model freezing

### ISSUE THREAD

**Issue by Hanminghao** [Jiangbo-Shi/ViLa-MIL#4]
A very good job you mentioned that you froze the Image encoder and Text encoder for the pre-trained model, but I don't seem to find the corresponding model freeze code in the code. Looking forward to your reply.

**Comment by Jiangbo-Shi** [comment]
Thanks for your question. The image encoder is utilized to extract the patch features in an offline way; The parameter of the text encoder is not updated. Only the defined prompt embeddings are learnable. For more specific details, please refer to this work [CoOp](https://arxiv.org/pdf/2109.01134).
