### ISSUE TITLE
Extract Patch Features

### ISSUE THREAD

**Issue by CYing18** [Jiangbo-Shi/ViLa-MIL#5]
![image](https://github.com/Jiangbo-Shi/ViLa-MIL/assets/103263202/07bdc3da-1623-48d0-a160-ee69fd325e1f)
I've encountered an issue while running patch_extraction.py, which seems to be due to the missing nn_encoder_arch in the feature_extraction/patch_extraction_utils.py file when it's called. Could you please provide the complete file and its description? Thank you!

**Comment by Jiangbo-Shi** [comment]
Thanks. I am sorry that this folder was omitted. The nn_encoder_arch folder has been uploaded now.
