### ISSUE TITLE
N in formulas 6 and 7

### ISSUE THREAD

**Issue by lijinda22** [Jiangbo-Shi/ViLa-MIL#6]
Exceptional work! 
However, in the course of studying this paper, it is objectively reasonable to say that these two values should probably be Np, respectively, I think.
![image](https://github.com/Jiangbo-Shi/ViLa-MIL/assets/93063410/fabf0446-7978-4354-b7da-0e733b9a7e19)

**Comment by Jiangbo-Shi** [comment]
We express our sincere gratitude for your meticulous revision. The correct values should be $N_p$. We will provide a corrected illustration in the readme file of this project and prepare a new online version of the paper to address this mistake. Thank you again.
